import pywinauto
import pyautogui
import time

class WideImageViewer:
    def __init__(self):
        self.title = "BZ-X800 Wide Image Viewer"

    def wait_for_viewer(self, max_delay_time):
        """
        Waits for the viewer to become available and returns the delay time.
        """
        start_time = time.time()
        while True:
            windows = pywinauto.Desktop(backend="win32").windows() # Connects to Windows Desktop using the pywinauto library
            matching_windows = [win for win in windows if self.title in win.window_text()] # Matches for multiple window titles of the name "BZ-X800 Wide Image Viewer"
            if matching_windows:
                break
            time.sleep(0.1)
        delay_time = min(time.time() - start_time, max_delay_time) # Calculates delay time based on max delay time of the image viewer
        return delay_time

    def name_files(self, naming_template, placeholder_values, xy_name, delay, filepath, channel_orders_list):
        """
        Names files based on the given naming template, placeholder values, XY name, delay, filepath, and channel orders list.

        Parameters:
            naming_template (str): The naming template for the file names.
            placeholder_values (dict): A dictionary containing placeholder values for each XY sequence.
            xy_name (str): The XY name.
            delay (float): The delay time.
            filepath (str): The filepath to save the images.
            channel_orders_list (list): A list containing the order of the channels that were imaged.
        """
        windows = pywinauto.Desktop(backend="win32").windows()
        matching_windows = [win for win in windows if self.title in win.window_text()]

        for i in range(len(matching_windows)): # Processes multiple channels generated by the image viewer
            last_window = matching_windows[i] # Selects the last opened window
            last_window.set_focus() # Focuses it to make it the active window

            self.click_file_button(last_window) # Clicks the file button to begin export
            self.export_in_original_scale() # Exports the image in original scale

            if i == 0 and filepath != "": # For the first run, the program will set the filepath to the filepath specified by the user during the config
                pyautogui.press('tab', presses=6)
                pyautogui.press('enter')
                pyautogui.write(filepath)
                pyautogui.press('enter')
                pyautogui.press('tab', presses=6)
                print(f"Filepath set to: {filepath}")

            channel = channel_orders_list[i]
            file_name = naming_template.format(C=channel, **placeholder_values[xy_name])
            print(f"Naming file: {file_name}")
            time.sleep(1)
            pyautogui.write(file_name)
            time.sleep(1)
            pyautogui.press('tab', presses=2)
            time.sleep(1)
            pyautogui.press('enter')

            self.close_image(delay, channel)

    def click_file_button(self, window):
        """
        Clicks the file button in the multiple opened wide_image_viewer images using pywinauto.
        """
        app = pywinauto.Application(backend="uia").connect(handle=window.handle)
        main_window = app.window(auto_id="MainForm", control_type="Window")
        toolbar = main_window.child_window(title="toolStrip1", control_type="ToolBar")
        file_button = toolbar.child_window(title="File", control_type="Button")
        file_button.click_input()

    def export_in_original_scale(self):
        """
        Simulates keyboard input to export the image in the original scale. Fastest way to export the image.
        """
        pyautogui.press('tab', presses=4)
        pyautogui.press('enter')
        pyautogui.press('tab', presses=1)
        pyautogui.press('enter')

    def close_image(self, delay, channel):
        """
        Closes the image after a specified delay. Fastest way to close the image.
        """
        time.sleep(delay) # Delay calculated from max delay time
        pyautogui.hotkey('alt', 'f4')
        pyautogui.press('tab', presses=1)
        pyautogui.press('enter')
        print(f"{channel} image closed.")